import { promises as fs } from 'fs';
import * as path from 'path';
import type { MicroTool, MicroToolResult, ToolCategory } from './toolRegistry';

export interface ProviderManifestTool {
  id: string;
  name: string;
  description: string;
  triggers?: string[];
  tags?: string[];
  category?: ToolCategory;
  steps?: Array<Record<string, unknown>>;
  schema?: {
    type?: 'object';
    properties?: Record<string, { type: string; description: string; enum?: string[] }>;
    required?: string[];
  };
  handlerRef: string;
  handlerConfig?: Record<string, unknown>;
}

export interface ProviderHandlerContext {
  providerId: string;
  tool: ProviderManifestTool;
}

export type ProviderHandlerFactory = (
  tool: ProviderManifestTool,
  context: ProviderHandlerContext
) => (args: Record<string, unknown>) => Promise<MicroToolResult>;

export type ProviderManifest = ProviderManifestTool[];

const handlerFactories = new Map<string, ProviderHandlerFactory>();

function registerDefaultHandlerFactories(): void {
  if (handlerFactories.size > 0) return;

  handlerFactories.set('static_result', (tool, context) => {
    const configured = tool.handlerConfig || {};
    return async () => ({
      ok: configured.ok !== false,
      data: configured.data ?? { providerId: context.providerId, toolId: tool.id },
      text: String(configured.text || `${tool.name} executed via provider manifest.`),
      warnings: Array.isArray(configured.warnings) ? configured.warnings.map(String) : [],
      error: configured.error ? String(configured.error) : undefined,
    });
  });

  handlerFactories.set('echo_args', (tool, context) => {
    const configured = tool.handlerConfig || {};
    return async (args) => ({
      ok: true,
      data: {
        providerId: context.providerId,
        toolId: tool.id,
        args,
        config: configured,
      },
      text: String(configured.text || `${tool.name} received args.`),
    });
  });

  handlerFactories.set('flow_template', (tool, context) => {
    const configured = tool.handlerConfig || {};
    return async () => {
      const steps = Array.isArray(configured.steps)
        ? configured.steps
        : Array.isArray(tool.steps)
          ? tool.steps
          : [];
      const payload = {
        summary: String(configured.summary || `${tool.name} flow ready.`),
        findings: [],
        suggestedFixes: [],
        actions: [
          {
            type: 'replace_flow',
            flow: {
              name: tool.name,
              description: tool.description,
              backend: String(configured.backend || 'pyvisa'),
              deviceType: String(configured.deviceType || 'SCOPE'),
              steps,
            },
          },
        ],
      };
      return {
        ok: true,
        data: {
          providerId: context.providerId,
          toolId: tool.id,
          flow: payload.actions[0].flow,
        },
        text: `ACTIONS_JSON: ${JSON.stringify(payload)}`,
      };
    };
  });
}

export function registerProviderHandlerFactory(name: string, factory: ProviderHandlerFactory): void {
  registerDefaultHandlerFactories();
  handlerFactories.set(name, factory);
}

function toMicroTool(tool: ProviderManifestTool, providerId: string): MicroTool {
  registerDefaultHandlerFactories();
  const factory = handlerFactories.get(tool.handlerRef);
  if (!factory) {
    throw new Error(`Unknown provider handlerRef "${tool.handlerRef}" for ${tool.id}`);
  }

  const normalizedId = tool.id.startsWith('provider:')
    ? tool.id
    : `provider:${providerId}:${tool.id}`;

  return {
    id: normalizedId,
    name: tool.name,
    description: tool.description,
    triggers: Array.from(new Set([...(tool.triggers || []), tool.name.toLowerCase(), tool.id.toLowerCase()])),
    tags: tool.tags || [providerId, 'provider'],
    category: tool.category || 'composite',
    schema: {
      type: 'object',
      properties: tool.schema?.properties || {},
      required: tool.schema?.required,
    },
    handler: factory(tool, { providerId, tool }),
    usageCount: 0,
    lastUsedAt: 0,
    autoGenerated: true,
  };
}

export async function loadProviderManifests(providersDir: string): Promise<MicroTool[]> {
  let files: string[] = [];
  try {
    files = (await fs.readdir(providersDir)).filter((file) => file.endsWith('.json'));
  } catch {
    return [];
  }

  const tools: MicroTool[] = [];
  for (const file of files) {
    try {
      const raw = await fs.readFile(path.join(providersDir, file), 'utf8');
      const manifest = JSON.parse(raw) as ProviderManifest;
      if (!Array.isArray(manifest)) continue;
      const providerId = path.basename(file, '.json');
      tools.push(...manifest.map((tool) => toMicroTool(tool, providerId)));
    } catch {
      // Skip malformed manifests.
    }
  }

  return tools;
}
