import { validateTool } from './toolValidation';

export type ToolCategory =
  | 'scpi_search'
  | 'scpi_lookup'
  | 'scpi_materialize'
  | 'scpi_verify'
  | 'scpi_override'
  | 'shortcut'
  | 'template'
  | 'planner'
  | 'rag'
  | 'validator'
  | 'instrument'
  | 'flow_action'
  | 'composite';

export interface MicroToolSchema {
  type: 'object';
  properties: Record<string, { type: string; description: string; enum?: string[] }>;
  required?: string[];
}

export interface MicroToolResult {
  ok: boolean;
  data?: unknown;
  text?: string;
  warnings?: string[];
  error?: string;
}

export type MicroToolHandler = (args: Record<string, unknown>) => Promise<MicroToolResult>;

export interface MicroTool {
  id: string;
  name: string;
  description: string;
  triggers: string[];
  tags: string[];
  category: ToolCategory;
  schema: MicroToolSchema;
  handler: MicroToolHandler;
  usageCount: number;
  lastUsedAt: number;
  successCount?: number;
  failureCount?: number;
  autoGenerated?: boolean;
  steps?: Array<Record<string, unknown>>;
}

export interface ToolSearchHit {
  tool: MicroTool;
  score: number;
  matchStage: 'trigger' | 'keyword' | 'semantic';
  debug?: {
    bm25Score?: number;
    semanticScore?: number;
    usageBoost?: number;
    successRate?: number;
    recencyBoost?: number;
    groupBoost?: number;
  };
}

export interface ToolRegistrationError {
  id: string;
  reason: string;
}

export interface BatchRegistrationResult {
  registered: number;
  rejected: ToolRegistrationError[];
}

export class ToolRegistry {
  private readonly tools = new Map<string, MicroTool>();
  private readonly triggerIndex = new Map<string, string[]>();
  private readonly registrationErrors: ToolRegistrationError[] = [];

  register(tool: MicroTool): void {
    const validation = validateTool(tool);
    if (!validation.valid) {
      const error = { id: String(tool?.id || '(unknown)'), reason: validation.reason };
      this.registrationErrors.push(error);
      throw new Error(`Invalid tool registration for ${error.id}: ${error.reason}`);
    }

    // FIX BUG-008: Always unregister old version FIRST to prevent partial state
    // If new registration fails, old is already cleaned up
    this.unregister(tool.id);
    
    try {
      this.tools.set(tool.id, tool);
      
      // Index triggers - if this fails, tool is still in tools map but triggers are missing
      // This is still better than the reverse (triggers pointing to missing tool)
      for (const trigger of tool.triggers) {
        const key = trigger.toLowerCase().trim();
        if (!key) continue;
        const list = this.triggerIndex.get(key) || [];
        if (!list.includes(tool.id)) list.push(tool.id);
        this.triggerIndex.set(key, list);
      }
    } catch (error) {
      // If trigger indexing fails, remove tool to keep state consistent
      this.tools.delete(tool.id);
      throw new Error(`Tool registration failed during trigger indexing: ${
        error instanceof Error ? error.message : String(error)
      }`);
    }
  }

  registerBatch(tools: MicroTool[]): BatchRegistrationResult {
    let registered = 0;
    const rejected: ToolRegistrationError[] = [];

    for (const tool of tools) {
      try {
        this.register(tool);
        registered += 1;
      } catch (err) {
        const reason = err instanceof Error ? err.message : String(err);
        const rejection = { id: String(tool?.id || '(unknown)'), reason };
        rejected.push(rejection);
        console.warn(`[MCP:router] Rejected tool registration for ${rejection.id}: ${reason}`);
      }
    }

    return { registered, rejected };
  }

  unregister(id: string): boolean {
    const tool = this.tools.get(id);
    if (!tool) return false;
    this.tools.delete(id);
    for (const trigger of tool.triggers) {
      const key = trigger.toLowerCase().trim();
      const list = this.triggerIndex.get(key);
      if (!list) continue;
      const filtered = list.filter((toolId) => toolId !== id);
      if (filtered.length > 0) this.triggerIndex.set(key, filtered);
      else this.triggerIndex.delete(key);
    }
    return true;
  }

  get(id: string): MicroTool | undefined {
    return this.tools.get(id);
  }

  getRegistrationErrors(): ToolRegistrationError[] {
    return [...this.registrationErrors];
  }

  has(id: string): boolean {
    return this.tools.has(id);
  }

  size(): number {
    return this.tools.size;
  }

  all(): MicroTool[] {
    return Array.from(this.tools.values());
  }

  byCategory(category: ToolCategory): MicroTool[] {
    return this.all().filter((tool) => tool.category === category);
  }

  lookupByTrigger(trigger: string): MicroTool[] {
    const key = trigger.toLowerCase().trim();
    const ids = this.triggerIndex.get(key) || [];
    return ids.map((id) => this.tools.get(id)).filter((tool): tool is MicroTool => Boolean(tool));
  }

  recordUsage(id: string): void {
    const tool = this.tools.get(id);
    if (!tool) return;
    tool.usageCount += 1;
    tool.lastUsedAt = Date.now();
  }

  recordSuccess(id: string): void {
    const tool = this.tools.get(id);
    if (!tool) return;
    tool.successCount += 1;
  }

  recordFailure(id: string): void {
    const tool = this.tools.get(id);
    if (!tool) return;
    tool.failureCount += 1;
  }

  exportForSearch(): Array<{
    id: string;
    text: string;
    category: ToolCategory;
    usageCount: number;
    successCount: number;
    failureCount: number;
  }> {
    return this.all().map((tool) => ({
      id: tool.id,
      text: [tool.name, tool.description, ...tool.tags, ...tool.triggers, tool.category].join(' '),
      category: tool.category,
      usageCount: tool.usageCount,
      successCount: tool.successCount,
      failureCount: tool.failureCount,
    }));
  }

  exportUsageStats(): Array<{
    id: string;
    usageCount: number;
    lastUsedAt: number;
    successCount: number;
    failureCount: number;
  }> {
    return this.all()
      .filter(
        (tool) =>
          tool.usageCount > 0 ||
          tool.successCount > 0 ||
          tool.failureCount > 0
      )
      .map((tool) => ({
        id: tool.id,
        usageCount: tool.usageCount,
        lastUsedAt: tool.lastUsedAt,
        successCount: tool.successCount,
        failureCount: tool.failureCount,
      }));
  }

  importUsageStats(
    stats: Array<{
      id: string;
      usageCount: number;
      lastUsedAt: number;
      successCount?: number;
      failureCount?: number;
    }>
  ): void {
    for (const stat of stats) {
      const tool = this.tools.get(stat.id);
      if (!tool) continue;
      tool.usageCount = stat.usageCount;
      tool.lastUsedAt = stat.lastUsedAt;
      tool.successCount = stat.successCount ?? 0;
      tool.failureCount = stat.failureCount ?? 0;
    }
  }
}

let _registry: ToolRegistry | null = null;

export function getToolRegistry(): ToolRegistry {
  if (!_registry) _registry = new ToolRegistry();
  return _registry;
}

export function resetToolRegistry(): ToolRegistry {
  _registry = new ToolRegistry();
  return _registry;
}
